---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demo
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: demo
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: nginx:1.23-alpine
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/templates
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: ${CONFIG_default_conf_template}
                  items:
                    - key: default.conf.template
                      path: default.conf.template
