---
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: ${NAMESPACE}
spec:
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: demo
  type: ClusterIP