{{- $ns := .Release.Name }}
{{- range $path, $_ :=  .Files.Glob .Values.configGlob }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ base $path}}
  namespace: {{ $ns }}
data:
{{ base $path | indent 2 }}: |
{{ $.Files.Get $path | indent 4 }}
{{- end }}
