---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-ds
  namespace: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: Always
          ports:
            - name: http
              protocol: TCP
              containerPort: 80
          volumeMounts:
            - name: config
              mountPath: {{ .Values.mountPath }}
              readOnly: true
          env:
            # https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/v1/conversion.go#L39-L48
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          projected:
            sources:
             {{- range $path, $_ :=  .Files.Glob  .Values.configGlob }}
              - configMap:
                  name: {{ base $path }}
                  items:
                    - key: {{ base $path }}
                      path: {{ base $path }}
             {{- end }}
