---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.service.type }}