---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
      protocol: TCP
      targetPort: http
  selector:
    app: {{ .Values.pods.label }}
  type: ClusterIP